# Generated by Django 3.2.5 on 2021-08-20 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='name',
            new_name='make',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='needs_fixin',
            new_name='notable_mods',
        ),
        migrations.AddField(
            model_name='car',
            name='mileage',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='model',
            field=models.CharField(default='', max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='repair_notes',
            field=models.CharField(default='', max_length=4000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='year',
            field=models.CharField(default='', max_length=400),
            preserve_default=False,
        ),
    ]
